BEGIN;

DROP TABLE IF EXISTS dsp.cookie CASCADE;

CREATE TABLE IF NOT EXISTS dsp.cookie(
	id UUID NOT NULL PRIMARY KEY,
	dsp_cookie_id UUID,
	ssp_cookie_id UUID,
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	modified_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL
);

DROP TABLE IF EXISTS ssp.cookie CASCADE;

CREATE TABLE IF NOT EXISTS ssp.cookie(
	id UUID NOT NULL PRIMARY KEY,
	ssp_cookie_id UUID,
	dsp_cookie_id UUID,
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	modified_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL
);

COMMIT;
